Attnam/ivan

Script/char.dat
I removed the names for the 2 asian sirens, they should default to siren now
=> Removed test1 and test2 sirens

Main/Source/gear.cpp, Main/Source/proto.cpp, Script/dungeon.dat, Script/item.dat
Makes whips breakable, since they were somewhat overpowered when they were indestructible.
Plus two other minor changes: 
* Decos' servants are changed to New Attnam team rather than Decos' team (doesn't make sense for them to side with him once the revolution starts)
* The "Are you sure you want to wish for ___?" prompt is now restricted to Wizard Mode, as it could easily be abused to get ommel liquids and the like. Wishing in a normal game will be the same as in 0.50 now.
=> Breakable Whips

Main/Source/char.cpp, Main/Source/command.cpp, Main/Source/nonhuman.cpp, Script/char.dat
=> merge Explore conflicts into master

FeLib/Source/graphics.cpp, FeLib/Source/whandler.cpp
(Contains changes discussed in #36.)
=> A couple of minor fixes to SDL2 code

Main/Include/lterra.h, Main/Include/lterras.h, Main/Include/stack.h, Main/Source/char.cpp, Main/Source/command.cpp, Main/Source/lsquare.cpp, Main/Source/lterras.cpp, Main/Source/miscitem.cpp, Main/Source/stack.cpp
See individual commit messages for more info.
=> Smarter 'open', 'close', and 'use key' command behavior

INSTALL, README
So people will know that IVAN works natively on that platform as well
these days.
=> Add OS X to README and INSTALL

FeLib/Source/error.cpp, README
- support email changed to `ivan-support@googlegroups.com`
- support website changed to `Attnam.com`
- programming contributions changed to `Github`
=> updates for support email and website

configure, configure.ac
=> Tell Autotools to compile as C++11

Main/Include/iconf.h, Main/Source/command.cpp, Main/Source/iconf.cpp, Main/Source/itemset.cpp, Main/Source/miscitem.cpp
=> Add toggle option for the smart open/close/apply

Main/Source/char.cpp
This is still annoying because you can be covered in blood even if you take 1 damage, but at least it's a step in the right direction.
=> Explosions only cause bleeding if they cut you

Main/Source/bodypart.cpp
This should allow things like skeletons to be detected by infravision.
Should fix https://github.com/Attnam/ivan/issues/24
=> Body parts are warm in they're burning

Main/Source/item.cpp
Burning beverages shouldn't be possible now, but someday, maybe there
will be a wooden mug or a leather wineskin or something.
Addresses https://github.com/Attnam/ivan/issues/56
=> Can't eat or drink burning objects

Main/Source/gods.cpp
Generally give gods more things to do and make an attempt to balance them against one another.
=> [WIP] More god effects

Main/Source/gods.cpp
=> Revert "[WIP] More god effects"

Main/Source/char.cpp
This is probably not the best solution, but it fixes #70 and makes the movement patterns affected by the issue look much better.
Maybe fixes #87 too?
=> Fix random movement pattern issue

Main/Include/item.h, Main/Source/char.cpp, Main/Source/item.cpp, Main/Source/stack.cpp
(If you know of any other typos, let me know so I'll edit them into this commit.)
=> Typo fixes

Scrshot/readme.txt, releasing.md
Since #78 it's created automatically when attempting to take a screenshot.
=> Remove Scrshot directory as it's no longer needed

Main/Source/miscitem.cpp
…instead of destroying them.
Fixes #110.
=> Add items inside itemcontainer to golem creator's inventory

Script/material.dat
Completes #117. Color taken from LIVAN
=> make Valpurium green

README, README.md
Original README is still preserved.
README.md is updated to include the "General gameplay" and "FAQ" sections from the original README. As well as the intro description.
=> Updating README.md

Main/Source/human.cpp
And also put out the character if they're on fire.
https://github.com/Attnam/ivan/issues/138
=> UNTESTED Priests can heal burns on body parts

Script/item.dat
=> Don't force "the" article for holy books

Script/material.dat
=> Revert "Nerf the perma stat gain from blink dogs and floating eyes a bit"

Main/Source/human.cpp
Attach/summon new limbs next.
Then heal burns.
Cure poisons etcetera.
Messages specific to master god.
=> Puts out flames first if the player character is burning.

Main/Source/gear.cpp
=> Fix acid shield message be verb forms and typo

Main/Source/human.cpp
=> Fix typo in necromancer quest narration

Main/Source/human.cpp, Script/char.dat
Addresses #128 
I'm not much of a writer so I'm fine if anyone has suggestions for her replies. (Also, not 100% sure on the back story - was Richel Decos sent by Petrus?)
=> Update priestess's friendly replies after Tweraif is freed

Main/Source/human.cpp, Script/char.dat
=> Revert "Update priestess's friendly replies after Tweraif is freed"

FeLib/Source/rawbit.cpp, Main/Include/database.h, Main/Include/god.h, Main/Source/command.cpp, Main/Source/database.cpp, Main/Source/game.cpp, audio/audio.cpp, audio/audio.h, audio/midiplayback.cpp
to make the build process less noisy :)
=> Fix some warnings

Main/Source/char.cpp
See conversation here https://attnam.com/topics/A-general-RFE-discussion-thread?page=1
=> Add periodic warnings for leprosy, per 4ab4

Main/Source/gods.cpp
Changes discussed [here](https://attnam.com/topics/God-tweaks) plus Mellis trades 4 items instead of 5.  Probably that's not a big enough nerf, but the other neutral gods are still mostly inferior.
=> More god effects

Main/Source/gear.cpp
eg. "She whip asks for the help of Scabies..." -> "Her whip asks for the help of Scabies..."
=> Fix pronoun in chameleon whip code

Main/Source/char.cpp
Fixes https://github.com/Attnam/ivan/issues/122 .
=> Metaalchemy, not metalchemy

Script/olterra.dat
=> Add sit message for iron maiden

Main/Source/char.cpp
=> Fix breaking poly wand explosion crash

FeLib/Include/save.h, FeLib/Source/save.cpp
Also remove some unused member functions.
It seems to work fine and the fstream functions mapped straightforwardly to the C ones, but probably better if someone tests it on their machine also before merging.
Closes #242.
=> Convert outputfile and inputfile to use fstream

Main/Source/game.cpp
=> Save game on exit when not deleting saves

FeLib/Include/graphics.h, FeLib/Source/graphics.cpp, Main/Include/iconf.h, Main/Source/iconf.cpp, Main/Source/igraph.cpp, igor/Source/igor.cpp
=> Add option to scale graphics by 2x

audio/audio.cpp
=> Fix AudioThread crash on exit

Script/dungeons/GloomyCaves.dat
Whoops, forgot to update these.
=> Fix EnterImages to use .png file extension

Script/dungeons/GloomyCaves.dat, Script/dungeons/UnderwaterTunnel.dat, Script/dungeons/XinrochTomb.dat, releasing.md
Now appears in Gloomy Caves, Underwater Tunnel and Tomb of Xinroch's Tomb
Updated Windows release guide to reflect file addition
=> Add music track "Dungeon3.mid" to the script

Main/Include/char.h, Main/Include/materia.h, Main/Source/char.cpp, Main/Source/database.cpp, Script/material.dat
Based on work by [vasiliy](https://attnam.com/users/vasiliy)/ketmar: http://repo.or.cz/k8-i-v-a-n.git/commit/0d2fb1562631925928535a66a718f27b4bdec4d9
=> Tin helmets block ESP

Main/Include/char.h, Main/Source/char.cpp
Add the player's weight after size, mostly as a fun info, but also because it's cool to see how much various creatures weight or how it changes with chopped off limbs.
=> Show player's weight in sidebar

FeLib/Include/whandler.h, FeLib/Source/whandler.cpp, Main/Source/char.cpp
=> Wait for keypress during voluntary action

Script/dungeons/XinrochTomb.dat
=> Add missing divine room config in ToX

Script/char.dat
=> Restore goblin berserker danger

Script/char.dat
To make them spawn more frequently. Thanks @fejoa for the solution
=> Ignore danger for skeleton puppies

Main/Source/game.cpp
https://github.com/Attnam/ivan/issues/368
I will mark it ready, until someone finds other glitches :)
=> (ready) bug fix for show items under

Main/Source/command.cpp
'b' is already used for going southwest. Let's make it 'B'.
=> Adjust the key for inscription for the NetHack scheme

Script/dungeons/Attnam.dat, Script/dungeons/GloomyCaves.dat, Script/dungeons/XinrochTomb.dat, Script/material.dat
Resurrected Xinroch's power is fine, but IMHO his level is a bit
lacking. Compare with Oree's lair, which has a design unseen anywhere
else in the game.
I suggest using a reversed TX Entry temple, ie. a reversed pentagram
where Xinroch can stand and fight. Fake UT1 entry for a bit of fun with
the player, then a fight in open area around the temple, and finally a
showdown with Xinroch in ruby-and-diamond temple.
With the new materials at our disposal, I changed the earth and wall
materials for Xinroch ghost and resurrected Xinroch levels a bit to have
a nice color scheme. :)
=> More interesting final TX level

Main/Include/message.h, Main/Source/main.cpp, Main/Source/message.cpp
Not a big deal, but the code looks more logical now.
=> Fix: memory leaks of message system and sound system

fantasyname/namegen.cc
Solved here: skeeto/fantasyname#11
Thanks to Christopher Wellons (@skeeto)
=> Use chrono for rng seed instead of random_device

Doc/Misc/ConfigSyntax.txt, FeLib/Include/feio.h, FeLib/Source/config.cpp, FeLib/Source/feio.cpp, FeLib/Source/festring.cpp
=> (ready): Allow "<" ">" "|" in fantasy name pattern

Main/Source/command.cpp
=> Fix bug introduced in clumsy merge of fluid rework #201

Script/olterra.dat
Ping #427
Until a more sophisticated fix comes along.
Prevents this somewhat rare but possible and frustrating bug: https://attnam.com/posts/29124
=> (ready) Make furnaces and anvils walkable

Main/Include/actions.h, Main/Source/char.cpp
=> Warn about severe injury from mustard gas while resting

Main/Source/actions.cpp
The game crashed randomly on mac.
=> Fix heap-use-after-free in go::Handle()

FeLib/Source/bitmap.cpp
A work-around for #503  (a blank dialog will be displayed) and any such issues.
=> Harden bitmap::Fill()

Main/Source/miscitem.cpp
=> Fix god repair/trade vials for vials

Main/Include/char.h, Main/Include/game.h, Main/Source/char.cpp, Main/Source/game.cpp, Main/Source/god.cpp, Main/Source/gods.cpp, NEWS
Largest effects of this PR:
* Balance some weaker and stronger gods (Scabies and Mellis, I'm looking at you).
* Prevent the player from becoming champion of both Valpurus and Mortifer. (And don't grant several Neerc Se-ulbs.)
* Increase effects of Wisdom on prayers.
=> God balance

Main/Source/cmdcraft.cpp
e.g. cut web and answer the question by pressing the spacebar
=> Fix crashes about recipe::whereRaw()

INSTALL
The travis ci has been doing this for a while.
btw it is time to discard SDL 1.x.
=> Doc: build IVAN in a custom folder

Main/Source/cmdcraft.cpp
esp. prevent making a magical item made of plant fiber
=> Further restrict the range of craftable items

Main/Source/proto.cpp, Script/item.dat
I have separated these commits from #538 for better tracking.
=> WIP: Clean up the Script/item.dat and improve database searching

Main/Source/nonhuman.cpp
=> Change Chamaleon to Chameleon

Main/Source/bugworkaround.cpp, Main/Source/char.cpp, Main/Source/cmdswapweap.cpp, Main/Source/database.cpp, Main/Source/game.cpp
Based on suggestions from lgtm.com: https://lgtm.com/projects/g/Attnam/ivan/alerts/?mode=list
=> Change '%d' to '%lu' and '%ld' where necessary

Main/Include/char.h, Main/Include/gear.h, Main/Include/item.h, Main/Include/lterra.h, Main/Include/lterras.h, Main/Include/miscitem.h, Main/Include/object.h, Main/Source/char.cpp, Main/Source/cmdcraft.cpp, Main/Source/gear.cpp, Main/Source/god.cpp, Main/Source/gods.cpp, Main/Source/human.cpp, Main/Source/item.cpp, Main/Source/lterra.cpp, Main/Source/lterras.cpp, Main/Source/miscitem.cpp, Main/Source/nonhuman.cpp, Main/Source/object.cpp, Main/Source/proto.cpp, Main/Source/script.cpp
This may prevent some memory corruption. Also added more checks for NULL pointers.
=> Clean up some code

cmake/FindSDL2.cmake
=> Warn about missing SDL2 frameworks

FeLib/Include/festring.h, FeLib/Source/festring.cpp, Main/Source/proto.cpp, Script/item.dat
* Allow more than one space between keywords.
* Fix aliases and reduce search conflicts among items.
* More aliases for searching items.
=> Improve item search algorithm

ci/osx/requirements.sh, ci/win/package.sh
* Fix ci/win: typo
* Fix ci/osx: remember to eject disk image
=> Update CI scripts

.github/workflows/build-ubuntu-nonwizard.yml, .github/workflows/build-ubuntu-wizmode.yml
By the pure mass of Bill's will...
=> GitHub actions setup
